[package]
name = "{{ project_name }}_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0", features = ["serde_derive"] }
anyhow = "1.0"
tonic = "0.11.0"
tracing = "0.1"